ethereum/glados

Cargo.lock
entity/Cargo.toml
entity/src/contentid.rs
entity/src/contentkey.rs
entity/src/test.rs
glados-core/src/types.rs
glados-monitor/src/lib.rs

Implements  a `get_or_create` AIP for ContentID and ContentKey database models that can be used to do lazy insertions.

WIP: simplify lazy creation of database records.

---

entity/src/contentkey.rs
glados-core/src/types.rs
glados-monitor/src/lib.rs

Convert the `glados-monitor` script to use the `get_or_create` function introduced in #10

convert to use get_or_create

---

glados-monitor/src/lib.rs

`glados-monitor` stopped finding new blocks after 3-4 blocks because it was hitting this `break`

glados-monitor: `continue` checking for new blocks instead of `break`ing out of loop

---

README.md
entity/src/contentkey.rs
entity/src/test.rs
glados-core/src/jsonrpc.rs
glados-monitor/src/lib.rs
glados-monitor/src/main.rs
glados-web/src/templates.rs

Panic when running `glados-monitor` against a local execution node.
```sh
$ cargo run -p glados-monitor -- --database-url sqlite::memory: follow-head --provider-url http://127.0.0.1:8545
```
The panic occurred in `contentkey::get_or_create()`, where an `Entity::find` Result was `unwrap()`ed.
The `run_glados_monitor()` initiates two never-ending loops:
- `follow_chain_head()`
- `retrieve_new_blocks()`
Rather than allow those loops to fail when an error is encountered, the loops are allowed to continue. 
- Errors are logged
- Where the loop cannot proceed due to an error, a `continue` moves to the next cycle.
The `retrieve_new_blocks()` control loop was determined by a `while let` on the `channel.recv()`. 
After the first successful loop, the function terminated and the channel was closed. …

Error logging

---

entity/src/contentaudit.rs
entity/src/contentid.rs
entity/src/contentkey.rs
entity/src/test.rs
glados-audit/src/lib.rs
glados-audit/src/main.rs
glados-core/src/jsonrpc.rs
glados-core/src/types.rs
glados-monitor/src/lib.rs
glados-monitor/src/main.rs
glados-web/src/lib.rs
glados-web/src/main.rs
glados-web/src/routes.rs
glados-web/src/templates.rs

The imports were a mixture of styles. 
Imports are 
- moved to sections, ordered as follows:
- std
- external
- workspace members
- module 
- alphabetical within each section
- grouped by Crate 
- as in https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#imports_granularity (which is still nightly-only)
- with the exception of any `prelude::*`, which are separate for clarity.

group and reorder crate imports

---

glados-monitor/src/main.rs

No database is created for in-memory db as noted in #30 
- ~~Implements option 2 outlined in the issue by detecting if the in-memory argument was passed and a running db migration to create the tables.~~
- ~~Implements option 3 outlined in the issue by detecting if all of the expected tables exist, and if any are missing, runs `Migrator::up` to create the tables.~~
- Implements option 3 outlined in the issue. It detects if the database contains no tables, and if so runs `Migrator::up` to create the tables.
This resolves the issue on `main` and also resolves the ("Unresolved") problem noted in #29

fix: Don't skip db init for in-memory db

---

Cargo.lock
entity/Cargo.toml
entity/src/contentaudit.rs
entity/src/contentid.rs
entity/src/contentkey.rs
entity/src/test.rs
glados-audit/Cargo.toml
glados-audit/src/lib.rs
glados-audit/src/main.rs
glados-core/Cargo.toml
glados-core/src/jsonrpc.rs
glados-monitor/Cargo.toml
glados-monitor/src/lib.rs
glados-monitor/src/main.rs
glados-web/Cargo.toml
glados-web/src/lib.rs
glados-web/src/main.rs

Use `anyhow` for error handling. Predominant benefit is quick and easy handling, especially in the context of
returning multiple error types within a single function. `anyhow` preserves error types, bubbling them up. 
The errors encountered in major code paths (such as loop blocks following the chain tip) are all unpacked and converted to
logs. This should ideally result in very few panics.
These are the rules that I used:
- Import `anyhow::Result` and use that everywhere instead of `std::Result`
- No use of `.unwrap()`, just `?` on the thing and `Result<()>` in signature.
- Except in `glados-web/src/routes.rs`, axum did not work well with anyhow for some reason at first glance. `unwrap()`s are left there for now.
- Don't put error types in the signature like `Result<(), SpecificError>`. …

use anyhow for error handling

---

SETUP_GUIDE.md

Adds a few additional descriptions to `SETUP_GUIDE.md`
- Clarify that the use of `/tmp` for db files is vulnerable on reboot
- Remove the requirement on pr 31 (db check for tables to determine init) and show use of `--migrate` flag for new empty db creation
- Descriptions for what source/dest each binary has for data

add clarification and description to guide

---

entity/src/executionbody.rs
entity/src/executionheader.rs
entity/src/executionreceipts.rs
glados-audit/src/lib.rs
glados-monitor/src/lib.rs

- Fixes #58. 
Makes `block_number` an `i32`. 
- Tested on fresh postgres
- Tested on fresh sqlite

Change block_number i64 -> i32

---

Cargo.lock
glados-web/Cargo.toml
glados-web/src/lib.rs
glados-web/src/main.rs

There was no indication of success/failure upon `glados-web` startup
Added welcome message `info!()` log:
```sh
...INFO  glados_web] Serving glados-web at <IP>:<Port>
```
Which reads the `SocketAddr` variable.
- Adds `tracing` and `env_logger` crates

add welcome message for glados-web

---

Cargo.lock
glados-audit/src/lib.rs
glados-web/Cargo.toml
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/contentkey_detail.html

Add information about what a key represents in `glados-web` UI. 
- Fixes #53.
- This PR is rebased on #59 
- Uses ethportal-api types in glados-web
- Recreates `HistoryContentKey` from `content_key` bytes that `glados-web` pulls from db.
- Uses `.to_string()` method to display content kind (header, body, receipts, accumulator)
- Performs a lookup of a block number if the content key is not for an accumulator 0x00, 0x01, 0x02.
Navigation is unchanged and is as follows:
- Main page (list of content_ids)
- content_id page (link to content_key)
- content_key page: (see below)
In addition to the audit results, the browser UI now shows:
```
Database ID: 9989
Content Key: 0x0031b4baa7fcd9b087c244eebfbeb8091dac37a44f719df5fc6c848c76ccd6cfdb
Content Id: …
```

Add metadata to glados web

---

README.md
glados-core/src/jsonrpc.rs

The `Header` content type was recently updated to `HeaderWithProof` - and Glados needs to be updated accordingly. Although, technically, the content keys remain (effectively) the same, and it's just the content value that's decoded differently, it seems a good idea to update Glados. I'll mark this pr as ready for review as soon as the next version of `ethportal-api` is released.

Add support for HeaderWithProof

---

glados-monitor/src/lib.rs

Small adjustment to logging message and level for glados-monitor imports.

Use info level logging for glados-monitor record import success message

---

Cargo.lock
entity/src/content.rs
entity/src/content_audit.rs
glados-web/Cargo.toml
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/content_dashboard.html
glados-web/templates/contentid_detail.html

Adds content to the glados-web dashboard. Partially resolves the following issue:
- #72
Tables have (where appropriate) columns:
- Result
- Sub-protocol
- Content key
- Content ID
- Content available at
- Audited at
Includes sections with each with a table containing 20 rows:
- Recent content with audits
- Recent content (no audit data in this table)
- Recent audits
- Recent audit successes
- Recent audit failures
A todo is left at the top of the page for audit statistics to be added in a different PR

add tables to dashboard for granular audit overview

---

glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/src/templates.rs

- Closes #64 
Handle errors in `glados-web` by logging and routing with HTTP response codes
- Removed unwrap() and expect() usage
- Entering incorrect routes is handled with response codes

add error handling to glados-web

---

Cargo.lock
entity/Cargo.toml
entity/src/content.rs
entity/src/test.rs
glados-audit/Cargo.toml
glados-audit/src/lib.rs
glados-core/Cargo.toml
glados-core/src/jsonrpc.rs
glados-monitor/Cargo.toml
glados-monitor/src/lib.rs
glados-web/Cargo.toml
glados-web/src/routes.rs

No corresponding issue
Replace all use of `hex` crate with either:
- `ethportal-api` method `.to_hex()` (on `OverlayContentKey`)
- `trin-utils::hex_*` methods
The `hex_encode()`-style methods in `trin-utils` provide a less error-prone way to use `0x`- prefixed strings inherent
to the Portal network. 
- The axum crate patch version is bumped to resolved a conflict arising from a pinned Axum-internal `Uint` crate version
- The ethportal-api is pointed to git as it is not publishable with internal git dependencies

use trin-utils hex methods

---

glados-audit/src/cli.rs
glados-audit/src/lib.rs
glados-audit/src/main.rs

- Fixes #67 
A CLI flag `--concurrency <n>` controls the number of threads that look at the Rx side of the channel and call Portal nodes for the content (ie perform the audit).
- The receiver of the multi-producer, single-receiver channel spawns threads as tasks arrive in the channel. 
- An atomic integer (`Arc<AtomicU8>`) keeps track of the number of active threads.
- **+1** Spawned tasks cause an **increment** of the atomic integer.
- **-1** Threads that either complete an audit or otherwise log an error and terminate cause a **decrement** the atomic integer.
- If the max threads specified by the CLI flag are active, the channel is not read from. A check is then performed every second in this situation.
- The Database connection is cloned for each thread. Concurrency is handled by …

Add concurrency to audits

---

glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/content_dashboard.html

- Closes #72 
Add a table of statistics to the top of `glados-web` dashboard
|Period|New content|Total audits|Total passes|Total failures|Pass rate|Failure rate|
|-|-|-|-|-|-|-|
|Hour|||||||
|Day|||||||
|Week|||||||
- Minor formatting change: Add vertical bar to "close" existing "tables" in the dashboard
- Change existing use of `ok_or()` (which eagerly evaluates - thus logging errors erroneously) to `ok_or_else()`, which is lazy (only log upon error).

add stats to glados-web dashboard

---

glados-web/src/routes.rs
glados-web/templates/content_dashboard.html

Fix the "rate" calculation for `glados-web` displaying audit stats.  Was previously always showing 0% due to order of operations.

fix rate display

---

Cargo.lock
glados-audit/Cargo.toml
glados-audit/src/cli.rs
glados-audit/src/lib.rs
glados-audit/src/main.rs
glados-audit/src/selection.rs
glados-core/Cargo.toml
glados-core/src/jsonrpc.rs

- Closes #74 
Adds HTTP capability to `glados-audit`, where currently IPC exclusively supported. 
- The transport is selected with a new `--transport <ipc/http>`. 
- Transport configuration uses the existing `--ipc-path <path>` flag and a new `--http-url <url>` flag.
- New `AuditConfig` for holding config derived from parsed CLI arguments.
This is the output from `cargo run -p glados-audit -- --help`
```console
Usage: glados-audit [OPTIONS] --transport <TRANSPORT>
Options:
-d, --database-url <DATABASE_URL>  [default: sqlite::memory:]
-i, --ipc-path <IPC_PATH>          
-u, --http-url <HTTP_URL>          
-t, --transport <TRANSPORT>        [possible values: ipc, http]
-c, --concurrency <CONCURRENCY>    number of auditing threads [default: 4]
-h, --help                         Print help …
```

add http transport

---

Cargo.lock
glados-monitor/Cargo.toml
glados-monitor/src/cli.rs
glados-monitor/src/main.rs

In order to add support for glados in our devops pipeline, it makes sense for it to be able to be configured to use the Pandaops nodes as a web3 data provider.
Tested this locally, and confirmed that it's able to retrieve data from pandaops.

Add support for panda ops provider

---

Cargo.lock

Fix for https://github.com/ethereum/glados/issues/106. The work was already done in Trin and required just an update of Cargo.lock to latest revision.

Update trin rev. to get BlockHeader type with Shanghai support

---

entity/src/content_audit.rs
entity/src/test.rs
glados-audit/src/lib.rs
glados-audit/src/selection.rs
glados-core/src/jsonrpc.rs
glados-web/assets/css/trace.css
glados-web/assets/js/trace/enr.js
glados-web/assets/js/trace/graph.js
glados-web/assets/js/trace/main.js
glados-web/src/lib.rs
glados-web/src/main.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/base.html
glados-web/templates/content_dashboard.html
glados-web/templates/contentaudit_detail.html
migration/src/lib.rs
migration/src/m20221114_143914_create_content_id_key_and_audit.rs
migration/src/m20230421_120832_add_audit_trace.rs

This PR adds a string column to the `contentaudit` schema, and renders the query graph on the audit details page for audits that have traces.
todo:

Add audit details page and audit tracing

---

entity/src/content_audit.rs
glados-audit/src/cli.rs
glados-audit/src/lib.rs
glados-audit/src/main.rs
glados-audit/src/selection.rs
glados-monitor/src/lib.rs

Add a subcommand to glados that executes a single one-off audit for previously audited content keys. This command is only functional for on-disk databases, passed in via a cli arg, and will not be effective on in-memory dbs. 
- Skipped support for all valid content keys (not just previously audited ones) to avoid complexity involved w/ looking up the block number via `web3` & inserting it into db. I figured if the use case is important, it can be added later
- Spent some time playing around with various configurations of the cli parser / subcommand structure. In the end this was the simplest design I could get to work.

Add specific single key audit

---

Cargo.lock
entity/src/node.rs
glados-core/Cargo.toml
glados-core/src/jsonrpc.rs
glados-web/Cargo.toml
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/content_dashboard.html

Use client info within dashboard

---

Cargo.lock
glados-core/Cargo.toml
glados-core/src/jsonrpc.rs

Updates jsonrpc.rs to use reth for IPC instead of net::UnixStream

Update glados-core to use reth for IPC instead of net::UnixStream

---

glados-audit/src/lib.rs
glados-core/src/jsonrpc.rs

Conditionally call `portal_historyTraceRecursiveFindContent` if auditing using trin node

Get content query trace from trin nodes

---

.gitignore

Jetbrains is a popular IDE for Rust not having ``.idea`` in gitignore creates extra time spent on avoiding commiting its files
Operating systems like Ubuntu 23.04 don't allow global pip installs by default making users instead use isolated virtual enviroments. Creating a ``venv`` adds 20k files and depending what software people use to commit switching between branches can spam the changed files view in visual git clients like GitHub Desktop forcing the developer to either manually add in command line, add the ignore locally every time they switch branches, or create a new venv each time.
Adding ``.idea`` and ``venv`` to .gitignore

Add ``.idea`` and ``venv`` to .gitignore

---

migration/src/m20230511_104811_create_record.rs

Unique index on seq_num prevents new reocrds with same seq-num to be added

Unique index on seq_num prevents new records with same seq-num to be added

---

glados-audit/src/validation.rs

Currently when an audit finishes with a payload that can't be validated, the content body is logged (with `WARN`) but not the key.
The value can be inferred from the surrounding context, but that becomes inexact and confusing with all of the concurrency going on. 
The content value is also removed because the errors themselves already contain the content value, so the value was being logged twice.

Log invalid content keys & remove duplicate content value log

---

glados-web/src/routes.rs
glados-web/templates/content_dashboard.html
glados-web/templates/index.html

This calculates the percentage without rounding in the stats, and moves the setting of how much to round it into the template.
I'm not sure why all the integer stats are in 32 bit instead of a more standard usize or u64. I went with f32 for the ratio purely out of cargo cult. My instinct would otherwise be to f64.
Also, the "per_100" seemed to obscure rather than help that this number is a percentage, so this includes a name change for the variables.

feat(web): show pass/fail % to tenths of a percent

---

glados-web/src/lib.rs
glados-web/src/routes.rs

Adds glados API route `/api/hourly_success_rate` for the purpose of integrating a discord bot to alert us when success rate drops.
Returns just a single JSON float value representing the percentage of success, or an error message on error if one occurs.

Adds hourly success rate API route for glados bot integration

---

SETUP_GUIDE.md

- One argument was counter-productive (don't turn stun off without a good reason)
- A few argements were just noisily resetting the default (see: ipc, bootnodes)
- A few arguments are no longer available (provider-related)
- Not sure why the discovery port was set to non-standard 9009, but it seems unnecessary.
The docs link was outdated and broken.

docs: update trin CLI launch docs

---

glados-audit/src/lib.rs
glados-core/src/jsonrpc.rs
glados-web/assets/css/trace.css
glados-web/assets/js/trace/enr.js
glados-web/assets/js/trace/main.js
glados-web/templates/contentaudit_detail.html

Allow trace feature for Fluffy and (potentially) other clients.
+ removed unused fields
+ all `snake_case` fields renamed to `camelCase`
+ ENR decoder for port and ip
+ support for displaying cancelled requests
Here's spec update: https://github.com/ethereum/portal-network-specs/pull/236

allow trace requests for fluffy

---

Cargo.lock
glados-web/Cargo.toml
glados-web/src/lib.rs
glados-web/src/routes.rs

The SQL which is most of this PR is just copy pasted from @KaydenML draft-PR so I am co-authoring the commit https://github.com/ethereum/glados/pull/176
There has been talks about possible deadzones on our network. But I didn't really think of it much till I ran the bridge in node count 16 mode and tried to gossip a block body 20 times or something. This is when I came to the realization what Mike and I believe Nick mentioned to check... a deadzone. I had an assumption that with the radius's on the network that couldn't be an issue, but after all maybe it could be a deadzone?
So this api checks if any nodes found in the latest census would accept the content_key if they were offered.

feat: api to check if content is in deadzone or will be accepted by network

---

migration/src/m20230511_104838_create_execution_metadata.rs

The index for execution metadata's block number column was made unique, which causes some problems because currently `Content` has a one-to-one relationship with `ExecutionMetadata`, where the index was assuming many-to-one. This fixes that.

Makes metadata block number index non-unique

---

glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/audit_dashboard.html
glados-web/templates/audit_table.html
glados-web/templates/base.html
glados-web/templates/index.html

This pr adds audit dashboard, which is similar to the current content dashboard except that it shows one pane of audits and allows them and their hour/day/week stats to be filtered by any combination of strategy, content type, and success. 
Similar idea as #156, except that only the data required is fetched from the server via an `/audits/filter/` endpoint, rather than all of the data being loaded and most of it being hidden.
closes #158 and #182

feat: Adds audit dashboard with filters

---

glados-web/src/routes.rs

`get_filtered_audit_stats` was mistakenly setting the audit rate to 0

fix: adds audit rate calculation to audit dashboard

---

glados-web/assets/css/glados_styles.css
glados-web/assets/js/piechart.js
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/base.html
glados-web/templates/census_explorer_page.html
glados-web/templates/index.html
glados-web/templates/paginated_census_list.html

fixes: https://github.com/ethereum/glados/issues/163
I implemented it so it looks pretty decent on mobile not 100% but nice to have.
Here are some pictures

feat: implement web view for DHT census data

---

.circleci/config.yml

Currently building and deploying glados is done manually this is tedious so lets automate it :smile: 
This CI is based off the one we have in Trin, rewritten a little so it is 4 jobs instead of 8

feat: add CI which builds glados's docker images

---

glados-web/templates/content_dashboard.html
glados-web/templates/index.html
glados-web/templates/network_dashboard.html

@mrferris 
After Images before using bootstrap

Styled Network-Dashboard

---

DOCKER_GUIDE.md
docker-compose.yml

This allows the user to use any node or service as long as it supports the EL JSON-RPC API.

Avoid Infura lock-in for docker-compose and add env to readme

---

DOCKER_GUIDE.md
docker-compose-clients.yml
docker-compose.yml

I went the route of using an `GLADOS_PORTAL_CLIENT` env var to select the client, as there are already several of those required anyhow. That way we can stick with just the default `docker-compose.yml`.
I used `extends` instead of `include` as the latter is only for fairly recent docker-compose versions.
Another option would be to create a docker compose file for each client and extends/include some common compose file. Not sure what is more idiomatic in Docker land.
~~This PR is in Draft because I haven't been able to fully test the final version as I'm hitting https://github.com/ethereum/glados/issues/205~~ Have been able to test it in the meanwhile.

Add support for Fluffy in the docker compose file

---

docker-compose-clients.yml
docker-compose.yml

Trin wasn't looking so good on the glados client diversity graph one major reason for this was NAT issues. Trin running using our docker compose setup had Trin running in a docker bridge network. This is somewhat of a similar situation the Trin nodes behind NAT would be faced with, a key note is techniques like UPNP don't work on docker bridge networks.
Regardless it looks like sigp/discv5 has already thought through some problems with nat traversal years ago.
In sigp/discv5 they have a IP:Port voting mechanism where the majority of different nodes that contact your node can end up changing you IP:Port depending on what they say. I do not know the effectiveness of it, it could have also been skewing/making things worse I am not 100% sure  yet.
On our testnet I could see warning such as …

fix: run portal-client on host instead of docker bridge network

---

Cargo.lock
entity/Cargo.toml
entity/src/audit_stats.rs
entity/src/lib.rs
glados-audit/src/cli.rs
glados-audit/src/lib.rs
glados-audit/src/main.rs
glados-audit/src/stats.rs
glados-core/Cargo.toml
glados-core/src/lib.rs
glados-core/src/stats.rs
glados-web/assets/js/stats_history.js
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/index.html
migration/src/lib.rs
migration/src/m20231107_004843_create_audit_stats.rs

This PR resolves #164, with a chart instead of the day segments. This aggregate data can be added in a subsequent PR.
The UI is a little rough around the edges, but good enough to be usable. 
The only question on the data gathered is whether I should continue calculating it as the average over the past hour. Maybe doing the average over a smaller period would be better. We've been using the "average over the past hour" metric when discussing glados performance, so that's what I went with.
Changes:
- Adds the `audit_stats` table, where stats for a bunch of different combinations of filters are recorded
- Moves stat calculation logic from `glados-web` to `glados-core` so that both `glados-web` and `glados-audit` can use 
- Adds the `periodically_record_stats` task to `glados-audit`
- Adds …

feat: adds audit stats recording and historical display

---

.dockerignore

Docker builds were taking a long time because the entire target directory was being copied to the builder, which is unnecessary because we're building from source on the builder.

fix: uses .dockerignore to skip copying target folder

---

docker-compose-clients.yml

disable poke was added to trin 3 months ago but we forgot to disable it on glados.
It is crazy how much traffic poke was generating from glados

fix: disable poke for trin docker compose

---

entity/src/audit_stats.rs
entity/src/content_audit.rs
glados-audit/Cargo.toml
glados-audit/src/cli.rs
glados-audit/src/lib.rs
glados-audit/src/selection.rs
glados-audit/src/stats.rs
glados-core/src/db.rs
glados-core/src/lib.rs
glados-core/src/stats.rs
glados-monitor/src/lib.rs
glados-web/assets/js/stats_history.js
glados-web/templates/audit_dashboard.html
migration/src/lib.rs
migration/src/m20240213_190221_add_fourfours_stats.rs

**What's the problem?**
The approach to 4444s stats taken in #230 requires pre-loading the DB with all 45mil+ content keys. This is quite an operational overhead. 
**What's the solution?**
This PR adds a dedicated `FourFours` audit strategy that has access to a `Web3` provider that it uses to randomly select  hashes for blocks between genesis and merge, stores their content keys in the DB, and then audits them. 
It also adds 4444s statistics to the front page, and the filtering option to the Audit Dashboard.

feat: adds fourfours strategy to glados-audit

---

glados-web/assets/js/stats_history.js

@njgheorghita:
> it would be nice if on the success rate graph, while hovering over the graph if it could display the time at which the cursor is that would be very helpful
Agreed 👍

feat: add time on hoverover to stats chart

---

docker-compose.yml

Previous PR gave `glados-audit` access to a block provider, `docker-compose.yml` doesn't pass this flag in

fix: add provider url to audit in compose

---

glados-audit/src/lib.rs
glados-core/src/jsonrpc.rs

Portal specs now define an error that's returned when content isn't successfully retrieved. Glados was expecting the previous `0x` value for data that isn't found.
**How was it fixed?**
A custom `From<jsonrpsee::Error> for JsonRpcError` implementation that checks the error code and creates a `ContentNotFound` error if applicable, otherwise falls back to the original `jsonrpsee::Error`.

feat: expects error for content not found

---

entity/src/census_node.rs
glados-web/assets/js/census-timeseries.js
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/base.html
glados-web/templates/census_explorer.html
glados-web/templates/enr_detail.html
glados-web/templates/index.html
glados-web/templates/single_census_view.html

**What was the problem?**
Census data was only visible at specific moments of time, rather than over any period of time. 
**How was it fixed?**
The census explorer page shows all nodes seen in the last 24 hours and their census status at each census over that period. 
Nodes are sorted by client string, and then by node ID. Unhighlighted Node IDs on the left axis are meant to be more searchable (Cmd F) than readable. 
Subsequent PRs will:
- show errors logged during census
- label trin testnet nodes (eg trin-ams-10)
Implements #200

feat: add census nodes timeline chart

---

glados-cartographer/src/lib.rs

Only a sliver of the network was being found by cartographer due to a logic change missed during review of #241.
**How was it fixed?**
Add the correct node ID (the one we're learning about rather than who we're learning about it from) to the set of known IDs.

fix: fix cartographer regression

---

glados-web/assets/js/stats_history.js

> feature request can we have latest & 4444s be the only default lines that show up on the dashboard graph? it's a bit crowded
- @njgheorghita

fix: update stats history to default to latest and 4444s

---

Cargo.lock
entity/src/content.rs
entity/src/test.rs
glados-audit/src/selection.rs
glados-core/src/db.rs
glados-monitor/Cargo.toml
glados-monitor/src/lib.rs

Fixes #238 
Also fixes issue where `glados-monitor` was using the time that the content key enters the DB, which could be many seconds after the block hit the chain.

fix: inaccurate content key timestamps

---

entity/src/content.rs
glados-audit/src/selection.rs
migration/src/lib.rs
migration/src/m20240322_205213_add_content_audit_index.rs

Some of our sql operations are inefficient and are taking seconds to run at scale while redlining cpu/mem on the glados host.
**What was fixed?**
1. `content` table has an index on `(protocol-id, content-key)`, but the `get_or_create` function was only doing a filter on `content-key` so this index wasn't being used and `content` creation was taking a long time. Filtering on `protocol-id` makes both indexes get used.
2. `content_audit` table was missing an index for the foreign key to the `content` table. Joining the `content_audit` table on the `content` table is necessary for the `latest` and `oldest` strategies, and those queries were taking a long time.
3. The `random` selection strategy had two inefficiencies: 1.) we were using `COUNT` to get all of the content IDs …

fix: improves sql efficiency

---

entity/src/content.rs

#246 fixed a problem with `content::get_or_create`. Turns out `content::get` had the same issue, and this fixes it.

fix: use index in content::get

---

.circleci/config.yml
Cargo.lock
README.md
entity/Cargo.lock
entity/Cargo.toml
entity/src/node.rs
entity/src/test.rs
glados-audit/Cargo.toml
glados-audit/src/cli.rs
glados-audit/src/selection.rs
glados-cartographer/src/cli.rs
glados-monitor/src/cli.rs
glados-monitor/src/main.rs
glados-web/src/cli.rs
glados-web/src/routes.rs
migration/Cargo.toml
migration/README.md
migration/src/lib.rs

**What's the problem?**
Our production deployments run on postgres, but all our tests run on sqlite. These two are different enough to make our tests (and thus CI results) not necessarily reflective of the behavior of our production deployment. 
**What's the solution?**
Using the `pgtemp` crate to create a postgres instance for unit tests to use. It uses a local installation of postgres instead of installing docker and then downloading postgres, which would make CI take much longer. 
This PR also removes all mentions of sqlite from the repo, and adds instructions for quickly spinning up a local postgres instance via docker.

feat: use postgres instead of sqlite for tests & ci

---

docker-compose-clients.yml

Fluffy also has this cli option but it never got added here in the docker images.

Disable poke for fluffy glados client

---

README.md

It was missing the environment variable flag, so gave this error in the shell:
```
docker: invalid reference format: repository name must be lowercase.
```
(trying to interpret POSTGRES_PASSWORD=password as the repository)

doc: fix postgres launch command in readme

---

Cargo.lock
entity/src/content.rs
entity/src/test.rs
glados-audit/src/lib.rs
glados-audit/src/selection.rs
glados-audit/src/validation.rs
glados-core/src/db.rs
glados-core/src/jsonrpc.rs
glados-monitor/Cargo.toml
glados-monitor/src/beacon.rs
glados-monitor/src/cli.rs
glados-monitor/src/lib.rs
glados-monitor/src/main.rs

This PR adds glados support for beacon data.
Changes:
- Adds `glados-monitor follow-beacon-head` command
- Modifies `glados-audit` to audit content keys from any portal overlay (previously any content key would parsed as a `HistoryContentKey` and be passed to a `portal_history...` endpoint), including state and beacon.

Adds monitoring and auditing of beacon data

---

README.md
glados-web/assets/js/radiusdensity.js
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/templates/index.html

Fix #261 
Adds a chart to the home page, showing how much coverage there is in the best case.
Here's an example from a real census run on my machine a few days ago:
The basic approach is to split the keyspace into 256 1-byte buckets. Then show how many nodes fully cover that keyspace, and how much partial coverage there is of those buckets.
This mostly reuses the existing data from the node radius chart, plus a bit more precision in the radius calculation sent by the server.
Also, I added a tooltip to help you see which bucket is showing which data, and the precise value of coverage. I am a little unsatisfied with the method of identifying the bucket prefix (back-calculating from the x-value), but I couldn't find a better solution after digging a bit. I'm open to suggestions.
Note: there …

Add data coverage chart

---

glados-web/assets/js/radiusdensity.js
glados-web/assets/js/trace/enr.js

1. census scatterplot show the right color
2. show client name in audit detail page

fix: show shisui color and client name

---

docker-compose-angelfood.yml
docker-compose-clients.yml

We recently set up our first testnet angelfood.
we want to have a glados instance for it using glados.
In the PR I make a new docker compose file configured for running an instance of Glados for out testnet Angelfood. With state audit enabled along with extending our client docker compose file to be able to run other networks
It can be found here https://glados-angelfood.ethdevops.io/audits/

feat: angelfood docker compose file

---

entity/src/node.rs
glados-web/assets/js/censustimeseries.js
glados-web/src/routes.rs
glados-web/templates/census_explorer.html

- Adds fluffy team's node nicknames to census explorer
- Adds expanded trin team node nicknames to census explorer
- Adds number of nodes to the top of the page
- Fixes issue where no census during a 24 hour period stopped scrolling back to previous 24 hour period

chore: expand node nicknames

---

glados-audit/src/lib.rs
glados-audit/src/state.rs
glados-core/src/jsonrpc.rs

In glados we were using custom code for interacting with Portal Clients JSON-RPC. To PR updates glados to use our standard JSON-RPC interfaces through our `ethportal-api` crate

refactor: updated glados to use ethportal-api instead of custom json-rpc code

---

Cargo.lock
glados-audit/Cargo.toml
glados-web/Cargo.toml
glados-web/assets/css/trace.css
glados-web/assets/js/trace/graph.js
glados-web/assets/js/trace/main.js
glados-web/src/routes.rs
glados-web/templates/contentaudit_detail.html
migration/src/lib.rs
migration/src/m20240720_111606_create_census_index.rs

Implements #161
Query traces don't show any information about whether a given node should have had the data, according to its radius at the time of the trace.
**How was this fixed?**
A lookup is done to find in census data the radius for each node closest to the time at which the trace took place. This information is encoded within the `QueryTrace` object, and then visualized client-side.

feat: add query trace node radius interpolation

---

glados-web/assets/js/trace/main.js

Tested fix for the issue that briefly broke the audit trace viewing page.

fix: prevent front-end error on unknown trace radii

---

entity/src/node.rs
glados-web/assets/js/censustimeseries.js
glados-web/templates/base.html

Adds portal bootnodes from https://github.com/ethereum/portal-network-specs/blob/master/bootnodes.md to the census explorer and sorts them to the top.

feat: sort bootnodes to top of census explorer

---

Cargo.lock
Cargo.toml
entity/Cargo.toml
glados-audit/Cargo.toml
glados-cartographer/Cargo.toml
glados-core/Cargo.toml
glados-monitor/Cargo.toml
glados-web/Cargo.toml

Updating dependencies, like in https://github.com/ethereum/trin/issues/845
I also alphabetized, when I noticed it. I would love to use cargo-sort, but apparently it's not compatible with workspace dependencies.

Switch Cargo.toml in packages to use workspace dependencies

---

docker-compose-clients.yml
docker-compose.yml
entity/src/content.rs
entity/src/test.rs
glados-web/assets/js/censustimeseries.js
glados-web/assets/js/stats_history.js
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/templates/base.html
glados-web/templates/index.html
migration/src/lib.rs
migration/src/m20240814_121507_census_subnetwork.rs
migration/src/m20240919_121611_census_subnetwork_index.rs

Glados currently only gathers and displays census data for the history network. This PR:
- turns on state and beacon networks on glados's trin instance
- runs cartographer instances for state and beacon networks to gather census data
- adds a selector to the UI that filters and displays census data by network: history, state, or beacon, while filtering via an http param `?network=` on the backend.
Bonus: continues the migration toward raw SQL and simplifies the calls for readability and maintenance purposes. 
Implements #293 for census data.
Note that all audit data will still show history, which is a bit awkward (history audit data displayed next to beacon/state census data) but it will toggle audit data per network in the next PR.

feat: adds dashboard census-feature parity across beacon, history, state networks 

---

glados-cartographer/src/lib.rs

If `glados_cartographer` finds zero nodes it will run the census forever.
History census recently deadlocked mysteriously, which I now believe happened because of this. Trin may have been restarted and the census was initialized before the trin node had anything in its routing table.
Additionally, beacon network currently has zero nodes on it, so one single census will run forever. This change makes it so that censuses will continually run and pick up new nodes as they come online.

fix: allow census to conclude if zero nodes are found

---

docker-compose.yml
entity/src/content.rs
glados-audit/src/stats.rs
glados-core/src/stats.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/audit_dashboard.html
glados-web/templates/base.html
migration/src/lib.rs
migration/src/m20241010_151313_audit_stats_performance.rs

This PR:
- activates population of state root data for blocks 0 - 1 million via a new `glados_monitor_state` container in `docker-compose.yml`
- activates auditing of state root data via a new `glados_audit_state` container in `docker-compose.yml`
- implements toggling of the audit dashboard between history and state

feat: adds state audits & audit dashboard state filtering

---

.circleci/config.yml
Cargo.lock
Cargo.toml
README.md
entity/src/content.rs
entity/src/test.rs
glados-audit/Cargo.toml
glados-audit/src/lib.rs
glados-audit/src/selection.rs
glados-audit/src/state.rs
glados-audit/src/validation.rs
glados-core/Cargo.toml
glados-core/src/db.rs
glados-core/src/jsonrpc.rs
glados-monitor/src/cli.rs
glados-monitor/src/lib.rs
glados-monitor/src/main.rs
glados-web/src/routes.rs

(I think) I need the latest ethportal-api to parse the new query trace. I tried to force cargo to use the latest, but then glados-web wouldn't build for me locally.
~To start, this PR is making sure I don't just have a local build problem. After confirming that, I'll switch over to making glados build again.~

Build correctly, with the latest ethportal-api

---

glados-web/src/routes.rs

Currently `glados-web` is crashing when trying to decode a state content key because it assumes a `HistoryContentKey` that makes further operations 502.

fix: makes content dead zone api work for state and beacon content keys

---

glados-web/assets/css/trace.css
glados-web/assets/js/trace/main.js
glados-web/templates/contentaudit_detail.html

Fix #319 
In the audit detail page, show the peer as a red dot when a content transfer fails due to any of:
- utp connection failure/timeout
- utp transfer failure/timeout
- data determined to be invalid
---
I tested this locally with the three failure types on a single audit, and all three peers showed up red:
I hacked this temporary trace in:
```diff
diff --git a/glados-web/src/routes.rs b/glados-web/src/routes.rs
index dd8d156..99a0719 100644
--- a/glados-web/src/routes.rs
+++ b/glados-web/src/routes.rs
@@ -546,7 +546,12 @@ pub async fn contentaudit_detail(
}
};
-    let trace_string = &audit.trace;
+    let trace_string = r#"{"cancelled":[],
+  "failures":{
+   "0x11ee0e3a44e8977c02da63bd85ab1605f41e76ce9cb6b05f0af1a8bb3a072438":{"durationMs":12,"failure":"utpTransferFailed"},
+ …
```

feat(web): visualize transfer failures in audit

---

Cargo.lock
Cargo.toml
glados-audit/src/state.rs
glados-core/src/jsonrpc.rs

The json-rpc api changed calls with recursive_find_content to get_content (and the same with trace).
Update to get the latest ethportal-api with the changes.

chore: new ethportal-api with recursive_find -> get

---

Cargo.lock
Cargo.toml
glados-audit/src/state.rs
glados-core/src/jsonrpc.rs

updates the version of ethportal-api this update removes code paths which weren't included in the JSON-RPC return types like content-id which is an internal trin thing.

chore: update ethportal-api which updates ContentInfo return types

---

glados-web/templates/base.html

We were missing a bootstrap `navbar-toggler` element to open the navbar on mobile.

fix: show navbar on mobile

---

entity/src/content_audit.rs
glados-web/src/lib.rs
glados-web/src/routes.rs

Adds an endpoint exposing the content keys of audits that have failed in the last 24 hours. https://github.com/ethereum/glados/issues/297

feat: Adds `/api/failed-keys/` endpoint

---

Cargo.lock
Cargo.toml
glados-audit/Cargo.toml
glados-web/src/routes.rs

It uses a more recent version of eth-trie, which causes conflict errors with the locally imported version. Updating the local version is apparently trivial.
This is necessary to use the latest versions of trin.

chore: upgrade ethportal-api to latest

---

docker-compose.yml

No idea why this is done. I found it in a patch on the production server.
It seems like it should work. Mike, can you share context?

chore: remove provider from beacon monitor docker

---

docker-compose.yml

It was pinned like this on the production server. I have no other context for it.
Obviously we want to avoid having any production patches at all (among other things, it prevents deploying via ansible), so even if it's a short term fix for something, let's put the change in master.

chore: pin postgres to version 16.4 in docker

---

glados-monitor/src/beacon.rs
glados-monitor/src/cli.rs
glados-monitor/src/lib.rs
glados-monitor/src/main.rs

Currently the Beacon Monitor is hardcoded to use the ethPandaOps beacon node. This PR adds a new monitor command `follow-beacon` which receives `--beacon-base-url` allowing use of any beacon node.
The beacon nodes passed through `--beacon-base-url` may use HTTP basic authentication if the username and password are passed as part of the URL. Using environment variables for authentication can be added if needed.

feat: Pass Beacon base URL to Beacon Monitor

---

glados-web/assets/js/censustimeseries.js

Fixes #290, Firefox seems to handle transparent stroke differently than Webkit/Blink. The solution was to add color to the stroke (used the background color).
The stroke width also needed to be reduced, otherwise the strokes where to wide.

fix: Add color to Census Explorer Stroke 

---

entity/src/audit_stats.rs
entity/src/content_audit.rs
glados-audit/src/stats.rs
glados-core/src/stats.rs
glados-web/assets/js/stats_history.js
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/index.html
migration/README.md
migration/src/lib.rs
migration/src/m20241206_154045_add_beacon_and_state_audit_stats.rs

Display State and Beacon data (when those subprotocols are selected) both in the Stats table and Audit Success chart of the main Glados Dashboard
Pending:

feat: Compute and Display State and Beacon stats

---

entity/src/node.rs
glados-web/src/routes.rs

Display bootnodes in census explorer even if they have not been seen during the reported 24 hour period

feat: Persist bootnodes in census explorer

---

glados-web/assets/js/trace/main.js

The visualization was not loading because the targetId changed format from an integer to a hex string, which caused a JS crash.

fix(web): trace visualization crashfix

---

docker-compose-clients.yml

We default disable discv5 json-rpc a while back, not realizing that this is mandatory in glados usage. This PR enables it specifically on cli.

Enable discovery v5 JSON-RPC namespace for Fluffy client

---

glados-web/assets/js/trace/graph.js

Bug: When sorted by Node ID, the IDs closest to 0 would be rendered off-screen to the left.
Most of this is a refactor. The only thing that made any difference was adding a padding-left. I don't love the solution, but I couldn't find why the left of the svg was shifted left off the viewport in the first place. So this was all I could come up with. Open to suggestions!

fix(web): audit trace graph left align

---

glados-web/assets/js/trace/main.js

This PR makes the 
node id's in the contentaudit_detail.html page clickable so you can see more information about the node

feat: make node_id clickable on contentaudit_details page

---

README.md

Database tests couldn't run locally, because they couldn't find initdb. This change adds a section to the readme, about how to diagnose and fix this particular issue.

docs: fix for temp db in local test run

---

glados-core/src/stats.rs

Use the existing indices more effectively by:
- using a left join instead of inner join
- move the protocol_id condition into the join on the content table
Both of these help avoid full table scans, which can shave many seconds off of the longest queries.

perf: speed up audit select queries

---

.gitattributes
datasets/mainnet/blocks/premerge.csv

`datasets/mainnet/blocks/premerge.csv` contains mappings of hash to block number so that we don't have to look them up continuously

feat: add premerge.csv header mappings to lfs

---

entity/src/node.rs
glados-core/src/jsonrpc.rs

Updates bootnode list to include all public ultralight nodes.
Also adds ultralight to list of clients that support `trace`

Update Ultralight nodes list

---

entity/src/audit_result_latest.rs
glados-web/assets/js/audit_block_status.js

Now that audits of headers by block number are added, add it as an option to the Latest Block status graph.
Also changes some strings for plural/singular consistency throughout the main page.

chore(web): display headers by number for latest block status graph

---

Cargo.lock
docker-compose.yml
glados-audit/Cargo.toml
glados-audit/src/cli.rs
glados-audit/src/lib.rs
glados-audit/src/selection.rs

Now that block numbers and hashes for all pre-merge blocks are saved in the DB, use that table to source block hashes for 4444 audits instead of fetching one from an RPC

chore(audit): deprecate RPC for 4444 history

---

.circleci/config.yml
Cargo.lock
Cargo.toml
glados-audit/Cargo.toml
glados-audit/Dockerfile
glados-audit/src/selection.rs
glados-audit/src/validation.rs
glados-cartographer/Dockerfile
glados-cartographer/src/lib.rs
glados-core/Cargo.toml
glados-monitor/Cargo.toml
glados-monitor/Dockerfile
glados-web/Cargo.toml
glados-web/Dockerfile

ethportal-api 0.6.0 introduced ping extensions, so a couple of changes were needed to get node_radius.
This PR allows Glados to work with the latest Trin release, a follow up PR will actually use the data in Ping Extensions.
Note: Glados now requires rust 1.8.5

chore: update ethportal-api dependency to version 0.6.0

---

Cargo.lock
Cargo.toml

ethportal-api 0.7.0 added support for Protocol Versions. This will be needed for monitoring/graphing the protocol version of nodes on the network.
@Ktl-XV ping for review

chore: bump ethportal-api to 0.7.0 for Protocol Version support

---

DATABASES.md

This update fixes a broken link to the Ethereum Portal Network specs. The original URL no longer exists (returns a 404), likely due to a refactor in the folder structure of the target repository. The corrected link ensures that readers and developers are redirected to the correct data-types section in the history-network.md spec.

 Fix broken specification link in DATABASES.md

---

glados-core/src/stats.rs

The query that filtered the audits to display had a bug. But the bug did not break the page because data is read twice from the DB, created issue #393 to fetch the data only once later.

fix(web): fix the network filter on the Audit Dashboard

---

entity/src/census_node.rs
glados-web/assets/js/bar_graph.js
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/templates/clients.html

Adds a Protocol Version Support by client graph, that shows **all** supported versions of the Portal Protocol of nodes in the latest census broken out by client

feat(web): add Protocol Version Support by client graph

---

.circleci/config.yml

In #396 I noticed that CI was failing because the git checkout failed, because of going over the LFS quota. This isn't a complete solution, but at least unblocks testing on active PRs.

chore: disable lfs checkout in lint-build-test CI

---

.circleci/config.yml

Checking out branches requires a `/head` appended to the `CIRCLE_BRANCH` variable. All other branch runs of CI, like master, should just check out the `CIRCLE_BRANCH` unmodified. This fixes the bug that causes CI on master to fail.

fix: check out code on master CI correctly

---

.gitignore
glados-web/assets/js/area_graph.js

The failure chart in #396 often has long gaps between data, so a weekly chart was oddly zoomed in.
This update to `areaGraph()` forces a weekly chart to scale to the full week, ignoring which data is available.

feat(web): show full week in areaGraph weekly charts

---

glados-web/assets/js/area_graph.js

If data is sent by the server with a key not specified by seriesMetadata, then display it anyway with an Other name.

feat(web): areaGraph - show a default Other field

---

.circleci/config.yml

Also, make a reusable step for a cleaner circle config.
I'm not sure how to test this cleanly without a merge to master. I am not clear whether the built docker images will work without the premerge.csv. But I figure I'd get the PR started as a place to discuss.

fix: ignore lfs during CI docker builds

---

glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/templates/index.html

Fix #336 
TODO:
Gut check test with a couple different failure records locally:
This screenshot ^ is the combination of this PR, #403 and #404

feat: new internal transfer failure chart on dash

---

docker-compose.yml

Currently only the Random strategy runs for Beacon audits when using docker-compose.
This PR enables Latest Audits for Beacon

chore: enable beacon latest audits in docker compose

---

DOCKER_GUIDE.md
docker-compose-clients.yml
entity/src/census_node.rs
glados-core/src/jsonrpc.rs
glados-web/assets/js/censustimeseries.js
glados-web/assets/js/piechart.js
glados-web/assets/js/radiusdensity.js
glados-web/assets/js/trace/enr.js
glados-web/assets/js/trace/main.js
glados-web/templates/index.html

The fluffy client has been renamed to Nimbus Portal client. This commit adapts glados to that name change.
The docker image is also updated with a new tag.
Replaced every usage of fluffy in the code with nimbus. There appear to be several instances where the ENR is checked for the "f" value in the client field. I kept that in place but also added the "n" value. Currently 'f' is still written by Nimbus Portal clients, but once this change gets deployed, we change change it to write 'n' in the ENR. After that the check for 'f' can be removed in glados.

Name change of fluffy client to nimbus-portal

---

entity/src/census_node.rs

@carver pointed out I accidentally used the word "shisui" instead of samba in one place here is a PR to fix that. https://github.com/ethereum/glados/pull/426

fix: strum props name used Shisui instead of Samba

---

entity/src/audit_internal_failure.rs
entity/src/census_node.rs
glados-web/src/lib.rs
glados-web/src/routes.rs
glados-web/src/templates.rs
glados-web/templates/base.html
glados-web/templates/diagnostics.html

Often, we want to dig into the details of why certain clients are producing transfer failures. A next step from seeing them show up in the graph is to dig into the specifics: which client, what type of failure, and which audit triggered the failure. This new page lists all those things, linking to the audit.
TODO:

feat(web): add page with recent transfer failures

---

glados-web/templates/contentaudit_detail.html

Show "Trace not available" on audit page when we don't have a trace.

fix: show "trace not available"

---

entity/src/audit.rs
entity/src/content.rs
entity/src/enums/content_type.rs
glados-web/templates/audit_table.html

Showing content type instead of protocol is much more useful for audit table

feat: show content type instead of protocol in audit table

---

docker-compose.yml

The `version` attribute is obsolete, so I removed it.

feat: remove version from docker compose file

---

docker-compose-clients.yml

Support for eth API is removed in nimbus_portal_client. Without the removal of this flag the startup command will fail.
(Without headers on history network and without state network it is not feasible to provide a meaningful eth API. We do however default enable `web3_clientVersion` method for retrieval of the client version)

Docker: Remove eth API flag in cli options

---

docker-compose-clients.yml

Default RPC port was changed to 8565, not to conflict with EL RPC interfaces.
Assuming here that glados specifically uses 8545, we need to set it to that at cli options.
This was recently changed for our client, see also https://github.com/status-im/nimbus-eth1/pull/3700

Docker: define the nimbus_portal_client RPC port to 8545

---

docker-compose.yml

All requests will be failing for some time (until content is re-injected into network), so there is no point in doing many audits.
For now, one audit per second is enough.

feat: set audit frequenty to 1 per second in docker compose
