- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- entity/Cargo.toml
- entity/src/keyvalue.rs
- entity/src/lib.rs
- entity/src/node.rs
- entity/src/record.rs
- entity/src/test.rs
- glados-core/Cargo.toml
- glados-core/src/cli.rs
- glados-core/src/jsonrpc.rs
- glados-monitor/Cargo.toml
- glados-monitor/src/lib.rs
- glados-web/Cargo.toml
- glados-web/src/routes.rs
- glados-web/src/state.rs
- glados-web/src/templates.rs
- glados-web/templates/node_list.html
- migration/Cargo.toml
- migration/src/m20220101_000001_create_table.rs
- src/main.rs
> Add some tests

- entity/src/contentaudit.rs
- entity/src/contentid.rs
- entity/src/contentkey.rs
- entity/src/lib.rs
- entity/src/test.rs
- migration/src/lib.rs
- migration/src/m20221114_143914_create_content_id_key_and_audit.rs
Implement database models for content auditing
> Implement models for content auditing

- README.md
> rough sketch of a minimally useful README

- Cargo.lock
- entity/src/contentid.rs
- entity/src/test.rs
- glados-web/Cargo.toml
- glados-web/src/lib.rs
- glados-web/src/routes.rs
- glados-web/src/templates.rs
- glados-web/templates/content_dashboard.html
- glados-web/templates/contentid_detail.html
- glados-web/templates/contentid_list.html
Adds real list and detail views for content ids.
> flesh out list and detail views for contentid

- entity/Cargo.toml
- entity/src/contentkey.rs
- glados-web/src/lib.rs
- glados-web/src/routes.rs
- glados-web/src/templates.rs
- glados-web/templates/contentid_detail.html
- glados-web/templates/contentid_list.html
- glados-web/templates/contentkey_detail.html
- glados-web/templates/contentkey_list.html
Adds list and detail views for content keys
> Add list and detail views for content keys

- glados-web/src/cli.rs
- glados-web/src/main.rs
- glados-web/src/routes.rs
- glados-web/src/state.rs
- glados-web/src/templates.rs
- glados-web/templates/index.html
- glados-web/templates/node_list.html
The original web app did some trin IPC requests in my experimentation.  These have been removed.
> cleanup IPC path from web applications

- entity/src/record.rs
- glados-core/src/types.rs
- migration/src/m20220101_000001_create_table.rs
fixes #20 
Fixes the migrations for nodes and enrs
> Fix migrations

- glados-web/templates/content_dashboard.html
- glados-web/templates/contentkey_detail.html
> Small tweak to how content audit details are displayed

- glados-core/src/jsonrpc.rs
- glados-core/src/types.rs
- glados-monitor/src/lib.rs
Adds creation and tracking of content keys for the block body and block receipts
> add content keys for block body and receipts

- README.md
- glados-core/src/types.rs
- glados-monitor/src/cli.rs
- glados-monitor/src/lib.rs
- glados-monitor/src/main.rs
Creates a command to import the pre-merge accumulators into the database.
> Create command in glados-monitor to import pre-merge accumulators.

- glados-audit/src/lib.rs
> change glados-audit to use INFO for audit results

- glados-web/templates/content_dashboard.html
Bootstrap has some nice css formatting for tables that we weren't using
https://getbootstrap.com/docs/5.2/content/tables/
Added it.
> use bootstrap formatting

- glados-web/src/routes.rs
- glados-web/templates/content_dashboard.html
Adds the rate that audits are being performed to the dashboard display.
> Add audit rate

- glados-audit/src/validation.rs
See issue https://github.com/ethereum/glados/issues/103
> Fix HistoryContentValue deserialization of the raw SSZ content

- glados-web/src/routes.rs
Using the wrong node_id for querying
Use the database node.id value
> Fix node_detail view query

- glados-audit/src/lib.rs
There were a few things in the code for strategy weights that I wanted to cleanup
I did some minor refactoring.
> Cleanup strategy weights code

- Cargo.lock
- entity/Cargo.toml
- glados-audit/Cargo.toml
- glados-cartographer/Cargo.toml
- glados-monitor/Cargo.toml
- glados-web/Cargo.toml
- migration/Cargo.toml
Just a dependency version update I need upstream
> Update sea-orm to latest

- glados-web/src/routes.rs
When calculating the number of content/audits in the past hour/week/day, we were loading every single row and then counting the size of the returned vec, rather than just having the DB count it for us via `count`. 
Previously our stat query times looked like this on prod (with 3.9m audit rows):
Hour stats: Content: 134 ms, Audits: 542 ms, Passes: 153 ms
Day stats:   Content: 142 ms, Audits: 1844 ms, Passes: 240 ms
Week stats:Content: 358 ms, Audits: 2671 ms, Passes: 452 ms
with this change they look like:
Hour stats: Content: 189 ms, Audits: 364 ms, Passes: 366 ms
Day stats:   Content: 182 ms, Audits: 355 ms, Passes: 361 ms
Week stats:Content: 183 ms, Audits: 362 ms, Passes: 421 ms
> Improve scalability of stat calculations

- .circleci/config.yml
- Cargo.toml
- entity/Cargo.toml
- glados-audit/Cargo.toml
- glados-core/Cargo.toml
- glados-monitor/Cargo.toml
- glados-web/Cargo.toml
- glados-web/src/routes.rs
- migration/Cargo.toml
Reth ipc only support 1.70, update rust version to fix CI
> updated rust version because of reth ipc

- glados-web/assets/css/content_dashboard.css
- glados-web/assets/css/glados_pages.css
- glados-web/templates/content_dashboard.html
I ended up styling the Content_Dashboard page to match the style of the Main Page that i had styled on my previous PR.
> Styled-Content-dashboard-to-match-theme-of-main-page

- glados-core/src/jsonrpc.rs
Fixes #160
Tested successfully with fluffy node.
I was tempted to finish & merge #138 in order to fix the root issue here in a more long-term way. Decided to patch this and will thaw & merge that PR subsequently.
> Expects utpTransfer key in content response

- DOCKER_GUIDE.md
- README.md
- docker-compose.yml
- glados-audit/Dockerfile
- glados-cartographer/Dockerfile
- glados-core/src/jsonrpc.rs
- glados-monitor/Dockerfile
- glados-web/Dockerfile
- glados-web/src/lib.rs
Creates a deployment containing:
- Glados Audit
- Glados Monitor
- Glados Web
- Trin
- Postgres
> Adds docker deployment of glados

- docker-compose.yml
Adds restart policy to docker containers.
> always restart policy

- glados-web/assets/css/glados_styles.css
- glados-web/templates/base.html
- glados-web/templates/content_dashboard.html
- glados-web/templates/index.html
> Bootstrap Navbar Implementation

- glados-web/templates/contentaudit_detail.html
- glados-web/templates/contentkey_detail.html
Fixes everything mentioned in #192 and #193
> fix: add strategy to the audit page & content key page

- SETUP_GUIDE.md
We are removing sqlite support so transitioning the setup docs to postgres.
I also changed everything so it uses http instead of ipc, as it is a pain to switch and being able to copy paste from here is nice. Most glados programs don't support ipc anyways.
> chore: update setup for postgres + added cartographer

- glados-web/assets/css/glados_styles.css
- glados-web/assets/js/trace/enr.js
- glados-web/assets/js/trace/main.js
- glados-web/templates/enr_detail.html
> Decoded Enr Viewer

- glados-web/templates/content_dashboard.html
> Content Dashboard mobile compatible and looks nice on mobile devices

- glados-web/templates/network_dashboard.html
> Network Dashboard Now Looks Nice On Mobile Devices

- glados-web/templates/enr_detail.html
- glados-web/templates/node_detail.html
> Styled node details page

- glados-web/templates/audit_dashboard.html
- glados-web/templates/audit_table.html
> Audit dashboard now looks nice on mobile devices

- glados-web/templates/enr_detail.html
- glados-web/templates/node_detail.html
> Removed detail view link from node details page and enr details page

- glados-web/assets/js/radiusdensity.js
- glados-web/templates/index.html
> Index page dimensions fix

- entity/src/content_audit.rs
- glados-audit/src/lib.rs
- glados-monitor/src/lib.rs
- glados-web/src/lib.rs
- glados-web/src/routes.rs
Fixes #205 
First commit is main purpose of this PR
Second commit fixes some `cargo fmt` discrepancies
> fix: stops crash on main page if no census in DB

- glados-web/assets/js/radiusdensity.js
> Radius charts x axis cut off fix

- glados-web/assets/js/radiusdensity.js
This PR is reliant on PR 221 https://github.com/ethereum/glados/pull/221
> Color coded nodes based on there client teams color in discord

- .circleci/config.yml
- Cargo.toml
- entity/Cargo.toml
- glados-audit/Cargo.toml
- glados-audit/Dockerfile
- glados-cartographer/Dockerfile
- glados-core/Cargo.toml
- glados-monitor/Cargo.toml
- glados-monitor/Dockerfile
- glados-web/Cargo.toml
- glados-web/Dockerfile
- glados-web/src/routes.rs
- migration/Cargo.toml
- migration/src/m20230511_104804_create_node.rs
- migration/src/m20230511_104814_create_content.rs
Updating the rust version and fixing the clippy warnings.
> chor: update rust version to 1.75.0

- glados-audit/src/selection.rs
**What was the problem?**
The `4444s` strategy put content keys for premerge blocks in the DB and then audits them. The `latest` strategy was picking these keys up to audit before the `4444s` strategy could audit them.
**Fix**
Latest strategy now sticks to post merge blocks only.
> fix: prevents latest strategy from picking up premerge keys

- glados-web/src/lib.rs
#220 mistakenly changed the glados web port to 3002, this reverts it back
> fix: revert glados-web port to 3001

- entity/src/audit_stats.rs
- glados-web/assets/js/stats_history.js
- glados-web/src/routes.rs
adds ability to scroll back week-by-week on glados success stats
> feat: audit stats history pagination by week

- glados-audit/src/selection.rs
**What was the problem?**
With millions of content keys in the DB, prod selection for the latest audit strategy had started to take 10-50 seconds.
The reason is that we were expecting an index on a `content_audit` column to find non-existent `content_audit` rows once we joined the `content` and `content_audit` tables to find content with no audits. 
**What was the fix?**
Used an anti-join pattern instead, which can make use of the `content_audit::content_key` index.
Also limited the content that the query will search to the last 24 hours to further limit the scanning necessary. 
Brings latest lookup times in prod with millions of content keys from 10-50 seconds to ~60ms.
> fix: improve latest performance

- glados-web/assets/js/piechart.js
> Color coded piechart based on there client teams color

- entity/src/record.rs
Temporary fix to prevent sequence numbers that overflow an i32 from crashing cartographer. 
Subsequent PR will migrate to allow a u64.
> fix: prevent error in cartographer on large sequence number ENRs

- glados-web/templates/contentkey_detail.html
> feat: add nodes that will accept count on contentkey_detail page

- entity/src/record.rs
the temporary solution in #258 used the incorrect value for the i32::MAX
> fix: temp seq no overflow fix

- glados-web/assets/js/piechart.js
> feat: show client shisui correctly

- glados-web/assets/js/radiusdensity.js
- Dynamic y-axis size (sorry I missed that on the merge of #261 )
- Ignore large nodes
> Data coverage chart v1.1

- glados-web/assets/css/glados_styles.css
- glados-web/assets/js/explanations.js
- glados-web/assets/js/stats_history.js
- glados-web/templates/index.html
Adds question mark icons to the top right of each homepage graph that show an explanation when clicked.
Looking for review on the explanations, which are on `index.html`.
> feat: adds question mark buttons for showing explanations of homepage graphs

- README.md
- glados-web/assets/css/glados_styles.css
- glados-web/assets/js/radiusdensity.js
- glados-web/assets/js/stats_history.js
- glados-web/templates/index.html
Checklist item on #286 -- I added some titles for the charts
Any thoughts on the names? I'm thinking it should be "Audit Success, by week" since you can page it.
---
Side note: I had to run an audit in order to generate data and make sure that the title didn't overlap. I didn't see a section in the readme to run the audit, so I figured it out and added a quick one. Any suggestions for how to improve that section?
> Dashboard chart titles

- glados-web/src/routes.rs
Potentially fixes 502 error on glados. It will still be a mystery to me why the front-page is throwing a 502 while the logs point to the `/audit/id/` page failing.
> fix: prevents error on missing trace string

- entity/src/census.rs
- entity/src/census_node.rs
- glados-cartographer/src/cli.rs
- glados-cartographer/src/lib.rs
- migration/src/lib.rs
- migration/src/m20240814_121507_census_subnetwork.rs
Adds `--subnetwork history|beacon|state` flag to cartographer
Subsequent PR will add census info to `glados-web`
#293
> feat: Adds cartographer support for beacon and state networks

- glados-web/assets/js/trace/graph.js
- glados-web/assets/js/trace/main.js
- glados-web/templates/audit_dashboard.html
- glados-web/templates/contentaudit_detail.html
Implements #301 
Toggle-able via selector, with permanent memory of preferred selection.
> feat: adds sorting of traces by node ID, with content ID marker

- glados-web/src/routes.rs
Something is loading random audits from the server and I still haven't figured out who or what, but once I pruned a bunch of old audits it made glados start panicking. This fixes that.
> fix: prevent panic on missing audit

- glados-web/src/routes.rs
`get_created_data_from_census_id` panics on a missing census ID. It ought not to, and glados's `routes.rs` needs a fuller culling of `unwrap`s.
> fix: prevent panic on missing census

- entity/Cargo.toml
- glados-audit/Cargo.toml
- glados-audit/Dockerfile
- glados-cartographer/Dockerfile
- glados-core/Cargo.toml
- glados-monitor/Cargo.toml
- glados-monitor/Dockerfile
- glados-web/Cargo.toml
- glados-web/Dockerfile
- migration/Cargo.toml
#321 increased the required rust version from 1.76 to 1.81
> chore: upgrade to rustc 1.81

- glados-audit/src/state.rs
State audits are failing due to 
`[2024-10-31T15:58:27Z ERROR glados_audit::state] Error during state audit. err=Error decoding node while walking trie: InvalidData content_key=AccountTrieNodeKey { path: Nibbles { nibbles: [] }, node_hash: 0x7f485a9dd816bcbfa98f6fa2334af80fabc71ac14a605685bde325c9eb1b5f9e }`
This was happening due to the usage of `ethportal_api::EncodedTrieNode` instead of `StateContentValue::decode` as is done within trin: https://github.com/ethereum/trin/blob/238e0b0b448f39409c34c8017c10f8a4212daee7/rpc/src/evm_state.rs#L169
> fix: decode account trie node values correctly

- docker-compose.yml
- entity/src/content_audit.rs
- glados-core/src/stats.rs
- glados-web/src/routes.rs
- glados-web/src/templates.rs
- glados-web/templates/audit_dashboard.html
- glados-web/templates/contentaudit_detail.html
Adds `glados_monitor_beacon` and `glados_audit_beacon` services to the docker compose and adds the UI for beacon audits.
> feat: add beacon auditing in docker compose service and glados UI

- glados-audit/src/lib.rs
- glados-core/src/jsonrpc.rs
This will be useful for inspecting the results of the trace, and selectively recording them to the database. For example, if some transfers fail during the trace (even if one ultimately succeeds), it's useful to track those intermediate failures.
(Some precursor work for #336 )
> refactor(core): give direct access to QueryTrace

- entity/src/record.rs
fix #366 
find Enr and insert Enr use different seq, so it will cause the insert error, only the seq bigger than i32::MAX will occor the error.
> fix: use wrong seq when find Enr

- glados-web/src/routes.rs
Currently a census where all nodes were offline (or Glados' Portal node couldn't find any) breaks the census explorer request (and view) for that 24 hour period, this PR will instead display it as a census with no online nodes.
> fix(web): allow for census with no online nodes

- Cargo.lock
- glados-web/assets/js/stats_history.js
- glados-web/src/lib.rs
> feat: enable random audit by default in dashboard graph

- entity/src/census_node.rs
- glados-web/assets/js/censustimeseries.js
- glados-web/assets/js/piechart.js
- glados-web/assets/js/radiusdensity.js
- glados-web/assets/js/trace/enr.js
- glados-web/templates/index.html
Samba is listed as Unknown on Glados
Add Samba.
Shisui was missing from a few places as well so I added them
> feat: add Samba

- glados-web/src/routes.rs
Fix #431 
Load time went from 17 seconds to 170 ms.
Note that the behavior changes slightly: it pulls the most recent census data that is up to 15 minutes after the audit time.
This is faster because we can do the sorting & limiting of the census nodes all in index by using the `surveyed_at` value directly, instead of the computed absolute difference.
Note that although we LIMIT 1 inside the census_node lookup, that is only limiting by record ID. Because each node may have multiple records, we only want the latest record for each node. So we still have to order by the time and apply DISTINCT node_id.
> perf(web): load radii of peers in audit details

- Cargo.lock
- Cargo.toml
- migration/Cargo.toml
- migration/src/lib.rs
- migration/src/m20230599_999999_create_census_tables.rs
- migration/src/m20240814_121507_census_subnetwork.rs
- migration/src/m20250317_183352_refactor_history_audit_stats.rs
Rolling back the DB migration doesn't work (few steps weren't correct).
Fixed the issue and added tests.
> fix: rolling back db migration

- glados-web/src/routes.rs
The subprotocol can be calculated from content_key, but current implementation is wrong. Instead of taking the entire first byte, it should only take first hex_decimal (only the highest 4 bits).
But that solution is a bit hacky, so I set the protocol id explicitly when content key is decoded.
> fix: protocol id calculation in is_content_in_deadzone

- entity/src/content_audit.rs
- glados-audit/src/lib.rs
- glados-audit/src/strategy/mod.rs
- glados-audit/src/strategy/sync.rs
Implement Sync strategy.
Small refactoring regarding audit selection, more to come in next PR.
> feat: implement sync strategy

- glados-core/src/stats.rs
Using left join improves performance.
> fix: use left join for stats query

- entity/src/node.rs
- glados-web/assets/js/censustimeseries.js
- glados-web/assets/js/piechart.js
- glados-web/assets/js/radiusdensity.js
- glados-web/assets/js/trace/enr.js
- glados-web/assets/js/trace/main.js
- glados-web/src/routes.rs
- glados-web/src/templates.rs
- glados-web/templates/contentaudit_detail.html
- glados-web/templates/diagnostics.html
- glados-web/templates/enr_detail.html
- glados-web/templates/node_detail.html
The "c" field in the ENR is not going to be supported in the long run.
Instead, we should switch to client related info from capabilities message.
> feat: use client from capabilities instead of use "c" from ENR

- glados-audit/src/strategy.rs
Audit both bodies and receipts.
First fetch header without doing audit, then start audit for bodies and receipts.
> feat: audit bodies and receipts
